### ISSUE TITLE
Refactorizar diagramas SOA

### ISSUE THREAD

**Issue by javiroberts** [javiroberts/das#2]
Primero hay q refactorizar las plantillas

**Comment by julianmacagno** [comment]
- Solicitar asistencia

1. Se agregó la comprobación de si los servicios están disponibles o no
2. Se agregó mostrar los disponibles y los no disponibles de forma separada (ya que Mariela requirió hacer algo con los no disponibles también).
3. Se agregó la tarea de geolocalización una vez que se selecciona la asistencia deseada.
4. Se eliminó el envío y validación del token ya que no es relevante en el diagrama.
5. Se agregó la validación si el pedido fué confirmado. En tal caso, se abre un chat con la entidad correspondiente.
6. Se agregó la cancelación de la asistencia al diagrama. Informándo al servidor en ese caso.
